package routers

import (
	"foodinfoGo/controllers"

	beego "github.com/beego/beego/v2/server/web"
)

func init() {
	beego.Router("/", &controllers.MainController{})
	beego.Router("/bookmarks", &controllers.MainController{})
	beego.Router("/login", &controllers.MainController{})
	beego.Router("/forget", &controllers.MainController{})
	beego.Router("/code", &controllers.MainController{})
	beego.Router("/resend", &controllers.MainController{})
	beego.Router("/signup", &controllers.MainController{})
	beego.Router("/oauth", &controllers.MainController{})
	beego.Router("/color", &controllers.MainController{})
	beego.Router("/icon", &controllers.MainController{})
	beego.Router("/store", &controllers.MainController{})
	beego.Router("/carte", &controllers.MainController{})
	beego.Router("/busdate", &controllers.MainController{})
	beego.Router("/fesdate", &controllers.MainController{})

	beego.Router("/Form/checkNewData", &controllers.FormController{}, "POST:CheckNewData")
	beego.Router("/Form/loginFormData", &controllers.FormController{}, "POST:LoginFormData")
	beego.Router("/Form/badgeFormData", &controllers.FormController{}, "POST:BadgeFormData")
	beego.Router("/Form/permissData", &controllers.FormController{}, "POST:PermissData")
	beego.Router("/Form/recordData", &controllers.FormController{}, "POST:RecordData")
	beego.Router("/Form/badgeData", &controllers.FormController{}, "POST:BadgeData")
	beego.Router("/Icon/searchData", &controllers.IconController{}, "POST:SearchData")
	beego.Router("/Icon/insertData", &controllers.IconController{}, "POST:InsertData")
	beego.Router("/Files/uploadData", &controllers.FilesController{}, "POST:UploadData")
	beego.Router("/Files/websiteData", &controllers.FilesController{}, "POST:WebsiteData")
	beego.Router("/Files/downloadData", &controllers.FilesController{}, "POST:DownloadData")
	beego.Router("/Files/transferData", &controllers.FilesController{}, "POST:TransferData")
	beego.Router("/Files/reviewData", &controllers.FilesController{}, "POST:ReviewData")
	beego.Router("/Login/checkUserData", &controllers.LoginController{}, "POST:CheckUserData")
	beego.Router("/Login/loginUserData", &controllers.LoginController{}, "POST:LoginUserData")
	beego.Router("/Forget/forgetUserData", &controllers.ForgetController{}, "POST:ForgetUserData")
	beego.Router("/Code/codeUserData", &controllers.CodeController{}, "POST:CodeUserData")
	beego.Router("/Resend/resendUserData", &controllers.ResendController{}, "POST:ResendUserData")
	beego.Router("/Signup/signupUserData", &controllers.SignupController{}, "POST:SignupUserData")
	beego.Router("/Home/pollingData", &controllers.MainController{}, "POST:PollingData")
	beego.Router("/Home/searchData", &controllers.MainController{}, "POST:SearchData")
	beego.Router("/Home/scrollData", &controllers.MainController{}, "POST:ScrollData")
	beego.Router("/Home/pingItemData", &controllers.MainController{}, "POST:PingItemData")
	beego.Router("/Home/sItemData", &controllers.MainController{}, "POST:SItemData")
	beego.Router("/Home/pingChatData", &controllers.MainController{}, "POST:PingChatData")
	beego.Router("/Home/sChatData", &controllers.MainController{}, "POST:SChatData")
	beego.Router("/Home/storeData", &controllers.MainController{}, "POST:StoreData")
	beego.Router("/Home/createData", &controllers.MainController{}, "POST:CreateData")
	beego.Router("/Store/searchData", &controllers.StoreController{}, "POST:SearchData")
	beego.Router("/Store/insertData", &controllers.StoreController{}, "POST:InsertData")
	beego.Router("/Carte/searchData", &controllers.CarteController{}, "POST:SearchData")
	beego.Router("/Carte/addMenuData", &controllers.CarteController{}, "POST:AddMenuData")
	beego.Router("/Carte/insertData", &controllers.CarteController{}, "POST:InsertData")
	beego.Router("/Busdate/searchData", &controllers.BusdateController{}, "POST:SearchData")
	beego.Router("/Busdate/addWeekData", &controllers.BusdateController{}, "POST:AddWeekData")
	beego.Router("/Busdate/insertData", &controllers.BusdateController{}, "POST:InsertData")
	beego.Router("/Fesdate/searchData", &controllers.FesdateController{}, "POST:SearchData")
	beego.Router("/Fesdate/insertData", &controllers.FesdateController{}, "POST:InsertData")
}
